/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Meetings } from "./Meetings";
import { MeetingsCountArgs } from "./MeetingsCountArgs";
import { MeetingsFindManyArgs } from "./MeetingsFindManyArgs";
import { MeetingsFindUniqueArgs } from "./MeetingsFindUniqueArgs";
import { CreateMeetingsArgs } from "./CreateMeetingsArgs";
import { UpdateMeetingsArgs } from "./UpdateMeetingsArgs";
import { DeleteMeetingsArgs } from "./DeleteMeetingsArgs";
import { MeetingsService } from "../meetings.service";
@graphql.Resolver(() => Meetings)
export class MeetingsResolverBase {
  constructor(protected readonly service: MeetingsService) {}

  async _meetingsItemsMeta(
    @graphql.Args() args: MeetingsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Meetings])
  async meetingsItems(
    @graphql.Args() args: MeetingsFindManyArgs
  ): Promise<Meetings[]> {
    return this.service.meetingsItems(args);
  }

  @graphql.Query(() => Meetings, { nullable: true })
  async meetings(
    @graphql.Args() args: MeetingsFindUniqueArgs
  ): Promise<Meetings | null> {
    const result = await this.service.meetings(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Meetings)
  async createMeetings(
    @graphql.Args() args: CreateMeetingsArgs
  ): Promise<Meetings> {
    return await this.service.createMeetings({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Meetings)
  async updateMeetings(
    @graphql.Args() args: UpdateMeetingsArgs
  ): Promise<Meetings | null> {
    try {
      return await this.service.updateMeetings({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Meetings)
  async deleteMeetings(
    @graphql.Args() args: DeleteMeetingsArgs
  ): Promise<Meetings | null> {
    try {
      return await this.service.deleteMeetings(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
