/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Notifications } from "./Notifications";
import { NotificationsCountArgs } from "./NotificationsCountArgs";
import { NotificationsFindManyArgs } from "./NotificationsFindManyArgs";
import { NotificationsFindUniqueArgs } from "./NotificationsFindUniqueArgs";
import { CreateNotificationsArgs } from "./CreateNotificationsArgs";
import { UpdateNotificationsArgs } from "./UpdateNotificationsArgs";
import { DeleteNotificationsArgs } from "./DeleteNotificationsArgs";
import { NotificationsService } from "../notifications.service";
@graphql.Resolver(() => Notifications)
export class NotificationsResolverBase {
  constructor(protected readonly service: NotificationsService) {}

  async _notificationsItemsMeta(
    @graphql.Args() args: NotificationsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Notifications])
  async notificationsItems(
    @graphql.Args() args: NotificationsFindManyArgs
  ): Promise<Notifications[]> {
    return this.service.notificationsItems(args);
  }

  @graphql.Query(() => Notifications, { nullable: true })
  async notifications(
    @graphql.Args() args: NotificationsFindUniqueArgs
  ): Promise<Notifications | null> {
    const result = await this.service.notifications(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Notifications)
  async createNotifications(
    @graphql.Args() args: CreateNotificationsArgs
  ): Promise<Notifications> {
    return await this.service.createNotifications({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Notifications)
  async updateNotifications(
    @graphql.Args() args: UpdateNotificationsArgs
  ): Promise<Notifications | null> {
    try {
      return await this.service.updateNotifications({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Notifications)
  async deleteNotifications(
    @graphql.Args() args: DeleteNotificationsArgs
  ): Promise<Notifications | null> {
    try {
      return await this.service.deleteNotifications(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
