/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { Faculty } from "../../faculty/base/Faculty";
import { Assignments } from "../../assignments/base/Assignments";
import { Exams } from "../../exams/base/Exams";

@ObjectType()
class Courses {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  courseName!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  courseCode!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  credits!: number | null;

  @ApiProperty({
    required: false,
    type: () => Faculty,
  })
  @ValidateNested()
  @Type(() => Faculty)
  @IsOptional()
  faculty?: Faculty | null;

  @ApiProperty({
    required: false,
    type: () => [Assignments],
  })
  @ValidateNested()
  @Type(() => Assignments)
  @IsOptional()
  assignmentsItems?: Array<Assignments>;

  @ApiProperty({
    required: false,
    type: () => [Exams],
  })
  @ValidateNested()
  @Type(() => Exams)
  @IsOptional()
  examsItems?: Array<Exams>;
}

export { Courses as Courses };
