/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { FacultyWhereUniqueInput } from "../../faculty/base/FacultyWhereUniqueInput";
import { Type } from "class-transformer";
import { AssignmentsCreateNestedManyWithoutCoursesItemsInput } from "./AssignmentsCreateNestedManyWithoutCoursesItemsInput";
import { ExamsCreateNestedManyWithoutCoursesItemsInput } from "./ExamsCreateNestedManyWithoutCoursesItemsInput";

@InputType()
class CoursesCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  courseName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  courseCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  credits?: number | null;

  @ApiProperty({
    required: false,
    type: () => FacultyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FacultyWhereUniqueInput)
  @IsOptional()
  @Field(() => FacultyWhereUniqueInput, {
    nullable: true,
  })
  faculty?: FacultyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AssignmentsCreateNestedManyWithoutCoursesItemsInput,
  })
  @ValidateNested()
  @Type(() => AssignmentsCreateNestedManyWithoutCoursesItemsInput)
  @IsOptional()
  @Field(() => AssignmentsCreateNestedManyWithoutCoursesItemsInput, {
    nullable: true,
  })
  assignmentsItems?: AssignmentsCreateNestedManyWithoutCoursesItemsInput;

  @ApiProperty({
    required: false,
    type: () => ExamsCreateNestedManyWithoutCoursesItemsInput,
  })
  @ValidateNested()
  @Type(() => ExamsCreateNestedManyWithoutCoursesItemsInput)
  @IsOptional()
  @Field(() => ExamsCreateNestedManyWithoutCoursesItemsInput, {
    nullable: true,
  })
  examsItems?: ExamsCreateNestedManyWithoutCoursesItemsInput;
}

export { CoursesCreateInput as CoursesCreateInput };
